# Etapa 1: construir la app con Maven
FROM maven:3.9.6-eclipse-temurin-21 AS build
WORKDIR /app
COPY . .
RUN mvn clean package -DskipTests

# Etapa 2: correr la app con JDK
FROM eclipse-temurin:21-jdk
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar

# Cambiar el puerto si es diferente
EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]
