spring.datasource.url=jdbc:postgresql://localhost:5432/bingo_db
spring.datasource.username=root
spring.datasource.password=Js25112005-
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Configuración de Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Configuración del servidor
server.port=8080

# Configuración JWT
bingo.app.jwtSecret=bWlDbGF2ZVNlY3JldGFQYXJhR2VuZXJhckpXVHNEZWJlU2VyTGFyZ2FZU2VndXJh
bingo.app.jwtExpirationMs=86400000

# Configuración de correo Gmail SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=jonatan25sanchez@gmail.com
spring.mail.password=fjdalzhhjehoistp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.debug=true
logging.level.bingo.unibague.demo.services.EmailService=DEBUG/